<div class="col-md-12">
    <div class="grid simple">
        <div class="grid-title no-border">
            <h4>Informações Gerais</h4>
        </div>
        <div class="grid-body no-border">
            <div class="row">
                <form action="<?php echo $this->baseUrl('/usuario/save/'); ?>" method="POST">
                    <div class="col-md-6">
                        <?php if($this->usuario['profile'] != 'gestor'){ ?>
                            <input type="hidden" name="profile_id" value="2">
                        <?php } else { ?>
                            <div class="form-group">
                                <label class="form-label">Perfil</label>
                                <div class="controls">
                                    <select id="profile_id" name="profile_id" style="width:100%">
                                        <option value="1">Gestor</option>
                                        <option value="2" selected="selected">Proponente</option>
                                    </select>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="form-group">
                            <label class="form-label">Nome Completo</label>
                            <span class="help">ex. "Luiz O. da Silva"</span>
                            <div class="controls">
                                <input class="form-control" id="name" name="name" type="text" required="required" maxlength="200">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="form-label">E-mail</label>
                            <span class="help">ex. "luiz@mail.com"</span>
                            <div class="controls">
                                <input class="form-control" id="email" name="email" type="email" required="required" maxlength="200">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="form-label">Telefone</label>
                            <span class="help">ex. "(11) 91234-5678"</span>
                            <div class="controls">
                                <input class="form-control" id="phone" name="phone" type="text" required="required" onkeyup="mascara(this, mtel)" maxlength="15">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="form-label">CPF</label>
                            <span class="help">ex. "123.456.789-01"</span>
                            <div class="controls">
                                <input class="form-control" id="num_document" name="num_document" type="text" required="required" onkeyup="mascara(this, mcpf)" maxlength="14">
                            </div>
                        </div>
                        <?php if($this->usuario['profile'] == 'gestor' || !isset($this->usuario['id'])){ ?>
                            <div class="form-group">
                                <label class="form-label">Senha</label>
                                <span class="help">obs. a senha deve conter no mínimo 6 caracteres</span>
                                <div class="controls">
                                    <input class="form-control" id="password" name="password" type="password" required="required" minlength="6">
                                </div>
                            </div>
                        <?php } ?>
                    </div>

                    <div class="clearfix"></div>
                    <div class="col-md-6 text-center">
                        <button type="button" class="btn btn-default" onclick="history.back()" >Voltar</button>
                    </div>
                    <div class="col-md-6 text-center">
                        <button type="submit" class="btn btn-success" id="bt-cadastro">Salvar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>