<div class="container-fluid">
   <div class="row-fluid">

      <div class="btn-toolbar"  align="right">
         <button class="btn btn-primary" onclick="javascript:document.location='<?php echo $this->baseUrl(); ?>/atendente/novo'"><i class="icon-plus"></i> Novo usuário</button>
      </div>

      <div class="btn-toolbar"  align="left">
         <form class="form-search" method="get">
            <input type="text" class="input-medium search-query" name="search" value="<?php echo $this->search; ?>">
            <button type="submit" class="btn" onclick="processModal('show', 'Buscando Atendente');">Buscar</button>
         </form>

      </div>

      <div class="well">
         <table class="table">
            <thead>
               <tr>
                  <th>#</th>
                  <th>Nome</th>
                  <th>Usuário</th>
                  <th>Perfil</th>
                  <th>Satus</th>
                  <th style="width: 120px;">Ações</th>
               </tr>
            </thead>
            <tbody>
               <?php if (count($this->rows) > 0) { ?>
                  <?php foreach ($this->rows as $row) { ?>
                     <tr onMouseOver="toggle(this,'#EDEDED');" onMouseOut="toggle(this,'#FFFFFF');">
                        <td><?php echo $row->id; ?></td>
                        <td>
                           <?php if ($row->superuser == 1) { ?>
                              <i class="icon-cog"></i> 
                           <?php } else { ?>
                              <i class="icon-user"></i> 
                           <?php } ?>
                           <?php echo $row->name; ?>
                        </td>
                        <td><?php echo $row->username; ?></td>
                        <td><?php echo $row->description; ?></td>
                        <td><?php echo $this->statusUser($row->enabled); ?></td>
                        <td>
                           <?php if ($row->superuser == -1 || $this->atendente['superuser'] == 1) { ?>
                              <a href="#resetarSenha" role="button" title="Resetar senha" onclick="resetarSenha(<?php echo $row->id; ?>, '<?php echo $row->name; ?>');">
                                 <i class="icon-asterisk">&nbsp</i>&nbsp</a>
                              &nbsp;| &nbsp;
                              <a href="<?php echo $this->baseUrl(); ?>/atendente/editar/i/<?php echo $row->id; ?>" title="Alterar"><i class="icon-pencil"></i></a>

                              &nbsp;| &nbsp;
                              <?php if ($row->enabled == 1) { ?>
                                 <a href="<?php echo $this->baseUrl(); ?>/atendente/ativar-desativar/i/<?php echo $row->id; ?>"  title="Desativar" 
                                    role="button" onclick="return confirm('Você realmente deseja desativar usuário <?php echo $row->name; ?>?');" >
                                    <i class="icon-eye-close">&nbsp</i>&nbsp
                                 <?php } else { ?>
                                    <a href="<?php echo $this->baseUrl(); ?>/atendente/ativar-desativar/i/<?php echo $row->id; ?>"  title="Ativar" 
                                       role="button" onclick="return confirm('Você realmente deseja ativar usuário <?php echo $row->name; ?>?');" >
                                       <i class="icon-eye-open">&nbsp</i>&nbsp
                                    <?php } ?>
                                 </a>

                                 <?php if ($this->atendente['superuser'] == 1) { ?>
                                    &nbsp;| &nbsp;
                                    <a href="<?php echo $this->baseUrl(); ?>/atendente/apagar/i/<?php echo $row->id; ?>"  title="Excluir" 
                                       role="button" onclick="return confirm('Você realmente deseja excluir <?php echo $row->name; ?>?');" ><i class="icon-remove">&nbsp</i>&nbsp</a>
                                    <?php } ?>
                                 <?php } ?>
                        </td>
                     </tr>
                  <?php } ?>
               <?php } ?>
            </tbody>
         </table>
      </div>
      <?php echo $this->partial('includes/paginator.phtml', array('pagination' => $this->pagination)); ?>      
      <!-- Resetar senha -->
      <div class="modal small hide fade" id="resetarSenha" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
         <form action="" name="formResetarSenha" id="formResetarSenha" method="post">
            <input type="hidden" name="senhaSearch" value="<?php echo $this->search; ?>">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
               <h3 id="myModalLabel">Resetar Senha: <b><span id="nomeResetarSenha"></span></b> </h3>
            </div>
            <p class="alert alert-info">
                      <small>
                           A senha deve conter:<br />
                           - 1 Caracter maíusculo<br />
                           - 1 Caracter minúsculo<br />
                           - 1 Número<br />
                           - 1 Caracter especial<br />
                           - Conter no mínimo 8 caracteres<br />
                      </small>
                   </p>
            <div class="modal-body">
               <p class="error-text" style="text-align: right">
                  <b>Nova Senha:</b> <input type="password" value="" class="input" name="senhaResetarSenha" id="senhaResetarSenha" />
                  <br />
                  <b>Confirmação Senha:</b> <input type="password" value="" class="input" name="confsenhaResetarSenha" id="confsenhaResetarSenha" />
               </p>
            </div>
            <div class="modal-footer">
               <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
               <button class="btn btn-success" type="submit">Resetar</button>
            </div>
         </form>
      </div>
      <!-- Resetar senha -->

   </div>
</div>
<script>
 
   
   function resetarSenha(id_user, nome){
      action = "<?php echo $this->baseUrl(); ?>/atendente/resetar-senha/i/" + id_user;
      document.formResetarSenha.action = action;     
      document.getElementById('nomeResetarSenha').innerHTML = nome;

      $('#resetarSenha').modal({
         backdrop: 'static',
         keyboard: false
      })
      $('#resetarSenha').modal('show');
   }
            

</script>