<div class="row login-container column-seperation">
    <div class="col-md-5 col-md-offset-1" style="padding: 30px">
        <br><br>
        <h2 style="color: #fff;">Conecte-se na <br/> <span style="font-weight: bold">Plataforma Pró-Livro</span></h2>
        <p style="color: #dedede;">
            Dê visibilidade aos seus projetos.
            <br><br>
            <a href="<?php echo $this->baseUrl('usuario/cadastro'); ?>">Cadastrar-se</a> agora mesmo, é grátis!
        </p>
        <br><br>
    </div>
    <div class="col-md-5">
        <br>
        <form class="login-form validate" id="login-form" method="post" name="login-form">
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="form-label" style="color: #dedede">E-mail</label>
                    <input class="form-control" id="usuario" name="usuario" type="email" required="required" autofocus="autofocus" title="Este campo é obrigatório!">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label class="form-label" style="color: #dedede">Senha</label> <span class="help"></span>
                    <input class="form-control" id="senha" name="senha" type="password" required="required" title="Este campo é obrigatório!">
                </div>
            </div>
            <div class="row">
                <div class="control-group col-md-6">
                    <div class="checkbox checkbox check-success">
                        <a href="javascript:;" id="esqueci-senha">esqueci minha senha</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <button class="btn btn-primary btn-cons pull-right" type="submit">Entrar</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div id="result"></div>
                </div>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#esqueci-senha').on('click', function (e) {
            e.preventDefault();
            $('#result').html('Enviado...');
            var mail = $('#usuario').val();
            $.post(baseUrl +'/usuario/esqueci-senha', {mail: mail}, function (data) {
                $('#result').html(data);
            })
        })
    });
</script>