<div class="col-md-12">
    <div class=" tiles col-md-12 no-padding">
        <div class="tiles">
            <div class="row">
                <div class="col-md-11 user-description-box  col-sm-9">
                    <h4 class="semi-bold no-margin"><?php echo $this->profile['nome']; ?></h4>
                    <br>
                    <p><i class="fa fa-phone"></i><?php echo $this->profile['telefone']; ?></p>
                    <p><i class="fa fa-envelope"></i><?php echo $this->profile['email']; ?></p>
                    <p><i class="fa fa-calendar"></i><?php echo $this->profile['cadastrado']; ?></p>
                </div>
            </div>

            <div class="tiles-body">
                <div class="row">
                    <div class="post col-md-12">
                        <?php foreach ($this->profile['ultimos_projetos'] as $dados) { ?>
                            <div class="info-wrapper">
                                <div class="username"><span class="dark-text" style="font-weight: bold"><?php echo $dados['nome']; ?></span></div>
                                <div class="info"><?php echo $dados['sintese']; ?></div>
                                <div class="more-details">
                                    <ul class="post-links" style="color: #FFF">
                                        <li><a href="javascript:;" class="muted" style="color:#FFF"><?php echo $dados['updated_at']; ?></a></li>
                                        <li><a href="<?php echo $this->baseUrl('/projeto/detalhes/i/'. $dados['id']); ?>" class="text-info" style="color: #FFF !important; text-decoration: underline">VER PROJETO</a></li>
                                        <li>[ <?php echo strtoupper($dados['status']); ?> ]</li>
                                    </ul>
                                </div>
                                <div class="clearfix"></div>
                                <br><br>
                            </div>
                        <?php } ?>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>