<div class="header navbar navbar-inverse">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="navbar-inner">
        <div class="header-quick-nav">
            <!-- BEGIN TOP NAVIGATION MENU -->
            <div class="pull-left">
                <!--LOGO-->
                <ul class="nav quick-section" style="margin-top: 0px">
                    <li class="quicklinks">
                        <a href="<?php echo $this->baseUrl('index'); ?>">
                            <img src="<?php echo $this->baseUrl('/images/logo.png'); ?>" class="logo"
                                 alt="" data-src="<?php echo $this->baseUrl('/images/logo.png'); ?>"
                                 data-src-retina="<?php echo $this->baseUrl('/images/logo.png'); ?>"
                                 style="margin: 0 !important; width: 70%" />
                        </a>
                    </li>
                </ul>

                <!--MENU-->
                <ul class="nav quick-section">
                    <li class="quicklinks" style="padding: 5px;">
                        <a href="http://plataforma.prolivro.org.br" class="" id="layout-condensed-toggle">Início</a>
                    </li>
                    <li class="quicklinks" style="padding: 5px;">&nbsp;</li>
                    <li class="quicklinks" style="padding: 5px;">
                        <?php if(!isset($this->usuario) || empty($this->usuario) || $this->usuario['id'] < 1){ ?>
                            <a href="<?php echo $this->baseUrl('/projeto'); ?>" class="">Projetos</a>
                        <?php } else { ?>
                            <div class="dropdown" style="padding: 4px 2px !important;">
                                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">Projetos&nbsp;&nbsp;<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->baseUrl('/projeto'); ?>">Listar Projetos</a></li>
                                    <li><a href="<?php echo $this->baseUrl('/projeto/meus-projetos'); ?>">Meus Projetos</a></li>
                                    <li class="divider"></li>
                                    <li><a class="text-success" href="<?php echo $this->baseUrl('/projeto/cadastro'); ?>">Cadastrar Projeto</a></li>
                                </ul>
                            </div>
                        <?php } ?>
                    </li>
                    <li class="quicklinks" style="padding: 5px;">&nbsp;</li>
                    <li class="quicklinks" style="padding: 5px;">
                        <div class="dropdown" style="padding: 4px 2px !important;">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">Mapeamento&nbsp;&nbsp;<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl('/mapa/brasil'); ?>">Por Estado</a></li>
                                <li><a href="<?php echo $this->baseUrl('/mapa/internacional'); ?>">Google Maps</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="quicklinks" style="padding: 5px;">&nbsp;</li>
                    <li class="quicklinks" style="padding: 5px;">
                        <a href="<?php echo $this->baseUrl('/projeto/cadastro'); ?>" class="">Cadastro</a>
                    </li>
                    <li class="quicklinks" style="padding: 5px;">&nbsp;</li>
                    <li class="quicklinks" style="padding: 5px;">
                        <a href="<?php echo $this->baseUrl('/usuario/cadastro'); ?>" class="">Usuário</a>
                    </li>
                    <?php if(strtolower($this->usuario['profile']) == 'gestor'){ ?>
                        <li class="quicklinks" style="padding: 5px;">&nbsp;</li>
                        <li class="quicklinks" style="padding: 5px;">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">Administração&nbsp;&nbsp;<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->baseUrl('/usuario/admin'); ?>">Usuários</a></li>
                                <li><a href="<?php echo $this->baseUrl('/projeto/admin'); ?>">Projetos</a></li>
                            </ul>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <!-- END TOP NAVIGATION MENU -->

            <!-- BEGIN CHAT TOGGLER -->
            <div class="pull-right">
                <ul class="nav quick-section ">
                    <li class="quicklinks" style="padding: 5px;">
                        <?php if(isset($this->usuario['id']) && !empty($this->usuario['id'])){ ?>
                            <a data-toggle="dropdown" class="dropdown-toggle  pull-right " href="#" id="user-options">
                                <?php echo $this->usuario['nome']; ?> &nbsp; <i class="fa fa-chevron-down" aria-hidden="true" style="font-size: 15px !important;"></i>
                            </a>
                            <ul class="dropdown-menu  pull-right" role="menu" aria-labelledby="user-options">
                                <li><a href="<?php echo $this->baseUrl('/usuario/perfil'); ?>"><i class="fa fa-user" aria-hidden="true" ></i>&nbsp;&nbsp;Meu Perfil</a></li>
                                <li><a href="<?php echo $this->baseUrl('/usuario/editar'); ?>"><i class="fa fa-pencil" aria-hidden="true" ></i>&nbsp;&nbsp;Editar</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->baseUrl('/usuario/logout'); ?>"><i class="fa fa-power-off" aria-hidden="true" ></i>&nbsp;&nbsp;Sair</a></li>
                            </ul>
                        <?php } else { ?>
                            <a class="pull-right" href="<?php echo $this->baseUrl('/usuario/login'); ?>" id="user-options">
                                Entrar&nbsp;&nbsp;<i class="fa fa-user aria-hidden="true" style="font-size: 15px !important;"></i>
                            </a>
                        <?php } ?>
                    </li>
                </ul>
            </div>
            <!-- END CHAT TOGGLER -->
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END TOP NAVIGATION BAR -->
</div>