<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <meta charset="utf-8" />
    <title><?php echo TITLE; echo (isset($this->title) && !empty($this->title)) ? " | ". $this->title : null; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="Plataforma Pró Leitura">
    <meta name="author" content="Cesar O Domingos <cesar_web@live.com>">
    <link rel="icon" href="<?php echo $this->baseUrl('images/icon.png'); ?>" sizes="192x192" />

    <script type="text/javascript">var baseUrl = "<?php echo $this->baseUrl(); ?>"</script>

    <?php
    echo $this->headLink()
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/font-awesome/css/font-awesome.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/pace/pace-theme-flash.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/bootstrapv3/css/bootstrap.min.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/bootstrapv3/css/bootstrap-theme.min.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/animate.min.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/jquery-scrollbar/jquery.scrollbar.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/bootstrap-datepicker/css/datepicker.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/bootstrap-timepicker/css/bootstrap-timepicker.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/bootstrap-select2/select2.css'))
        ->appendStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons')
        ->appendStylesheet($this->baseUrl('/bundle/webarch/css/webarch.css'))
        ->appendStylesheet($this->baseUrl('/bundle/assets/plugins/jquery-jvectormap/css/jquery-jvectormap-1.2.2.css'))
        ->appendStylesheet('https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css');

    echo $this->headScript()
        ->appendFile($this->baseUrl('/bundle/assets/plugins/pace/pace.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery/jquery-1.11.3.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/bootstrapv3/js/bootstrap.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-block-ui/jqueryblockui.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-unveil/jquery.unveil.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-scrollbar/jquery.scrollbar.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-numberAnimate/jquery.animateNumbers.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-validation/js/jquery.validate.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/bootstrap-select2/select2.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/js/chat.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/bootstrap-select2/select2.min.js'))
        ->appendFile($this->baseUrl('/bundle/webarch/js/webarch.js'))
        ->appendFile($this->baseUrl('/js/mask-er.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-jvectormap/js/jquery-jvectormap-1.2.2.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-jvectormap/js/jquery-jvectormap-brazil.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-datatable/js/jquery.dataTables.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/jquery-datatable/extra/js/dataTables.tableTools.min.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/datatables-responsive/js/datatables.responsive.js'))
        ->appendFile($this->baseUrl('/bundle/assets/plugins/datatables-responsive/js/lodash.min.js'))
        ->appendFile('https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js');
    ?>
</head>
<!-- END HEAD -->

<!-- BEGIN BODY -->
<body class="horizontal-menu">

<!-- BEGIN HEADER -->
<?php echo $this->render('includes/menu.phtml'); ?>
<!-- END HEADER -->

<!-- BEGIN CONTAINER -->
<div class="page-container row-fluid">
    <div class="page-content">
        <div class="content" style="padding-top: 83px !important; background-color: #424040">
            <div class="page-title">
                <i class="fa fa-angle-right" aria-hidden="true" style="font-size: 28px; color: #e0e0e0"></i>
                <h3 style="color: #e0e0e0; text-transform: uppercase; font-weight: bold;">
                    <?php
                        if(strstr($this->title, ' - ')){
                            $title = explode(' - ', $this->title);
                            echo $title[0] .' - <strong>'. $title[1] .'</strong>';
                        } else {
                            echo $this->title;
                        }
                    ?>
                </h3>
            </div>

            <?php echo $this->Resultadodeoperacoes(); ?>

            <div class="row">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>

    <footer style="padding: 10px">
        <p align="right" style="margin:0 0 0 10px">
            &copy; 2017 <a href="<?php echo SITE_URL; ?>" target="_blank">Plataforma Pró-Livro</a> Iniciativa do Instituto Pró-Livro.
            <sub><br/>Desenvolvida pela <a href="http://midiamix.publier.com.br" target="_blank">Midiamix Editora Digital</a></sub>
        </p>
    </footer>
</div>
<!-- END CONTAINER -->
</body>
</html>