<div class="col-md-12">
    <div class="grid simple">
        <div class="grid-title no-border">
            <div class="row">
                <div id="container">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <form method="post" class="text-center">
                            <div class="form-group">
                                <label for="nome">Nome do Projeto</label>
                                <input type="text" maxlength="100" name="nome" id="nome">
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary" value="Cadastrar Projeto">
                            </div>
                        </form>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </div>
    </div>
</div>