<div class="col-xs-12">
    <div class="col-md-12 well">
        <h2 style="margin-bottom: 25px">3º Passo - Instituições e Parcerias</h2>

        <div class="container col-md-12">
            <div class="row">
                <!-- Nome da Organização/Instituição -->
                <div class="col-md-12" style="padding-left: 0">
                    <div class="form-group">
                        <label for="instituicao"><h5>Organização/Instituição que promove/realiza o projeto?</h5></label>
                        <input type="text" class="form-control" id="instituicao" name="instituicao" placeholder="" maxlength="100"
                            value="<?php echo $this->project->organizacao_nome; ?>">
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Categoria da Organização/Instituição -->
                <div class="col-md-5" style="padding-left: 0">
                    <div class="form-group" style="padding-left: 0">
                        <h5>Em qual categoria(s) se enquadra essa Organização?</h5>
                        <?php
                        $arrCategoria = array(
                            "Cadeia produtiva do livro (editora, livraria etc.)",
                            "ONGs (organização não governamental)",
                            "Mídia (revista, jornal, site, mídia social, TV etc.)",
                            "Biblioteca - pública ou comunitária",
                            "Órgão público",
                            "Outra"
                        );

                        $outraValue = array();
                        foreach ($arrCategoria as $key => $value) {
                            $checked = "";
                            foreach ($this->project->organizacao_categoria as $row){
                                if($row->categoria == $value){ $checked = "checked='checked'"; }
                                if($row->categoria == 'Órgão público'){ $outraValue['Órgão público'] = $row->detalhe; }
                                if($row->categoria == 'Outra'){ $outraValue['Outra'] = $row->detalhe; }

                            }
                            if($value == 'Órgão público' || $value == 'Outra'){
                                ?>
                                <div style="margin-bottom: 5px;" class="clearfix">
                                    <div class="col-md-6" style="padding-left: 0">
                                        <div class="checkbox">
                                            <input type="checkbox" name="categoria[]" id="categoria<?php echo $key; ?>" value="<?php echo $value; ?>" <?php echo $checked; ?>>
                                            <label for="categoria<?php echo $key; ?>" style="font-size: 12px"><?php echo $value; ?></label>
                                        </div>
                                    </div>
                                    <div class="col-md-6" style="padding-left: 0">
                                        <input type="text" class="input-sm" id="categoria<?php echo $key; ?>detalhe" name="categoria_<?php echo ($value == 'Outra') ? 'outra' : 'orgao'; ?>_detalhe" placeholder="<?php echo ($value == 'Órgão público') ? 'Qual?' : null; ?>" maxlength="50"
                                            value=" <?php echo (isset($outraValue[$value])) ? $outraValue[$value] : null; ?>">
                                    </div>
                                </div>
                                <?php } else { ?>
                                <div class="checkbox">
                                    <input type="checkbox" name="categoria[]" id="categoria<?php echo $key; ?>" value="<?php echo $value; ?>" <?php echo $checked; ?>>
                                    <label for="categoria<?php echo $key; ?>" style="font-size: 12px"><?php echo $value; ?></label>
                                </div>
                            <?php } ?>
                        <?php } ?>
                    </div>
                </div>

                <!-- Parcerias e Apoios -->
                <div class="col-md-7">
                    <div class="form-group" style="padding-left: 0">
                        <h5>
                            Parcerias e Apoios&nbsp;&nbsp;
                            <span class="my-tooltip" data-toggle="tooltip" data-placement="top" title="Se estabeleceu parcerias para realizar o projeto, informe apoio e o nome instituição.">
                                <i class="fa fa-info-circle" aria-hidden="true"></i>
                            </span>
                        </h5>

                        <!-- Patrocinio -->
                        <div style="margin-bottom: 5px;" class="clearfix">
                            <div class="col-md-3" style="padding-left: 0">
                                <label for="categoria4" style="font-size: 12px">Patrocínio</label>
                            </div>
                            <div class="col-md-3" style="padding-left: 0">
                                <div class="input-group">
                                    <input type="text" id="parcerias_patrocinio_porcentagem" name="parcerias_patrocinio_porcentagem" placeholder="(%) Porcentagem" maxlength="3" min="0" max="100" onkeyup="mascara(this, mnum);"
                                        value="<?php echo $this->project->organizacao_parceiros->patrocinio_percentual; ?>">
                                    <span class="input-group-addon primary"><span class="arrow"></span> % </span>
                                </div>
                            </div>
                            <div class="col-md-6" style="padding-left: 0">
                                <input type="text" id="parcerias_patrocinio_instituicao" name="parcerias_patrocinio_instituicao" placeholder="Instituição" maxlength="100"
                                       value="<?php echo $this->project->organizacao_parceiros->patrocinio; ?>">
                            </div>
                        </div>

                        <!-- Apoio Tecnico -->
                        <div style="margin-bottom: 5px;" class="clearfix">
                            <div class="col-md-3" style="padding-left: 0">
                                <label for="categoria4" style="font-size: 12px">Apoio técnico <sub>(acessoria/consultoria)</sub></label>
                            </div>
                            <div class="col-md-9" style="padding-left: 0">
                                <input type="text" id="parcerias_apoiotecnico_instituicao" name="parcerias_apoiotecnico_instituicao" placeholder="Instituição" maxlength="100"
                                       value="<?php echo $this->project->organizacao_parceiros->apoio_tecnico; ?>">
                            </div>
                        </div>

                        <!-- Apoio Institucional -->
                        <div style="margin-bottom: 5px;" class="clearfix">
                            <div class="col-md-3" style="padding-left: 0">
                                <label for="categoria4" style="font-size: 12px">Apoio institucional</label>
                            </div>
                            <div class="col-md-9" style="padding-left: 0">
                                <input type="text" id="parcerias_apoioinstitucional_instituicao" name="parcerias_apoioinstitucional_instituicao" placeholder="Instituição" maxlength="100"
                                       value="<?php echo $this->project->organizacao_parceiros->apoio_institucional; ?>">
                            </div>
                        </div>

                        <!-- Outros -->
                        <div style="margin-bottom: 5px;" class="clearfix">
                            <div class="col-md-3" style="padding-left: 0">
                                <label for="categoria4" style="font-size: 12px">Outros</label>
                            </div>
                            <div class="col-md-9" style="padding-left: 0">
                                <input type="text" id="parcerias_outros_instituicao" name="parcerias_outros_instituicao" placeholder="" maxlength="100"
                                       value="<?php echo $this->project->organizacao_parceiros->outros; ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Equipe do Projeto -->
                <div class="col-md-12" style="padding-left: 0">
                    <div class="form-group">
                        <h5>Equipe do Projeto</h5>
                        <div class="row">
                            <?php
                            $arrTeam = array(
                                'equipe_coordenador' => 'Coordenador(es)',
                                'equipe_professor' => 'Professor(es)',
                                'equipe_educador' => 'Educador(es)',
                                'equipe_bibliotecario' => 'Bibliotecário(s)',
                                'equipe_voluntario' => 'Volunário(s)',
                                'equipe_mediador' => 'Agente(s)/Mediador(es) de leitura',
                                'equipe_outros' => 'Outro(s)',
                            );

                            foreach ($arrTeam as $key => $value){
                                $qtdEquipe = 0;
                                $detalheEquipe = null;
                                foreach ($this->project->project_team as $row){
                                    if($row->equipe == $key){
                                        $qtdEquipe = $row->quantidade;
                                        $detalheEquipe = $row->detalhe;
                                    }
                                }
                                ?>
                                <div class="col-md-6" style="padding-left: 0">
                                    <div class="form-group">
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" id="<?php echo $key; ?>" name="<?php echo $key; ?>" maxlength="12" placeholder="0" onkeyup="mascara(this, mdecimal)"
                                                value="<?php echo $qtdEquipe; ?>">
                                        </div>
                                        <?php if($key == 'equipe_outros'){ ?>
                                            <div class="col-md-8" style="padding-left: 0">
                                                <input type="text" class="form-control" id="<?php echo $key; ?>_detalhe" name="<?php echo $key; ?>_detalhe" placeholder="Outros(s)" maxlength="50"
                                                    value="<?php echo $detalheEquipe; ?>">
                                            </div>
                                        <?php } else { ?>
                                            <div class="col-md-8" style="padding-left: 0"><label for="<?php echo $key; ?>"><?php echo $value; ?></label></div>
                                        <?php } ?>
                                    </div>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- BOTÕES-->
        <div class="container col-md-12" style="margin-top: 10px">
            <div class="row">
                <div class="col-md-4 text-left">
                    <a href="javascript:;" class="btn btn-primary btn-md activate-step" data-step="2">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        2º PASSO
                    </a>
                </div>
                <div class="col-md-4 text-center">
                    <a href="javascript:;" class="btn btn-danger btn-md save">
                        <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
                        Salvar Rascunho
                    </a>
                </div>
                <div class="col-md-4 text-right">
                    <a href="javascript:;" class="btn btn-primary btn-md activate-step" data-step="4">
                        4º PASSO
                        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>