<div class="col-xs-12">
    <div class="col-md-12 well">
        <h2 style="margin-bottom: 25px">2º Passo - Expectativas e Localização</h2>

        <div class="container col-md-12">
            <div class="row">
                <!-- Abrangência e Localização-->
                <div class="col-md-8" style="padding-left: 0">
                    <h5>Abrangência e Localização</h5>

                    <div class="row">
                        <!-- Territorio -->
                        <div class="col-md-6">
                            <label for="territorio">País</label>
                            <select class="form-control select2 select2-offscreen" tabindex="-1" multiple="multiple" name="territorio[]" id="territorio"></select>
                        </div>


                        <!-- Regional -->
                        <div class="col-md-6 input-nacional">
                            <h5>Regional</h5>
                            <?php
                            $arrRegional = array("Norte", "Nordeste", "Centro-Oeste", "Sudeste", "Sul");
                            foreach ($arrRegional as $key => $value) {
                                ?>
                                <div class="checkbox check-default checkbox-inline" style="margin-left: 0">
                                    <input type="checkbox" class="regional" name="regional[]" id="regional<?php echo $key; ?>" value="<?php echo $value; ?>" <?php echo (strstr($this->project->localizacao_regional, $value)) ? "checked=''" : null; ?>>
                                    <label for="regional<?php echo $key; ?>" style="font-size: 12px"><?php echo $value; ?></label>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>

                    <div class="row input-nacional">
                        <!-- Estado -->
                        <div class="col-md-6" style="margin-bottom: 20px">
                            <label for="estados">Estados</label>
                            <select class="form-control select2 select2-offscreen" tabindex="-1" multiple="multiple" name="estados[]" id="estados"></select>
                        </div>

                        <!-- Cidades -->
                        <div class="col-md-6" style="margin-bottom: 20px">
                            <label for="cidades">Cidades</label>
                            <select class="form-control select2 select2-offscreen" tabindex="-1" multiple="multiple" name="cidades[]" id="cidades"></select>
                        </div>
                    </div>
                </div>

                <!-- Expectativas -->
                <div class="col-md-4">
                    <div class="form-group">
                        <h5>Expectativas com o Cadastro do Projeto</h5>
                        <?php
                        $arrExpectativas = array(
                            "Colaborar com o Mapa de Projetos",
                            "Inscrever um projeto no Prêmio",
                            "Divulgar novidades em Notícias e Fórum",
                            "Conhecer a Plataforma",
                            "Acesar notícias ou informações",
                            "Participar de fóruns ou redes sociais",
                            "Ser fonte de informação em entrevistas",
                            "Outra"
                        );

                        $outraValue = null;
                        foreach ($arrExpectativas as $key => $value) {
                            $checked = "";
                            foreach ($this->project->projeto_expectativa as $row){
                                if($row->expectativa == $value){ $checked = "checked='checked'"; }
                                if($row->expectativa == 'Outra'){ $outraValue = $row->detalhe; }

                            }
                            ?>
                            <div style="margin-bottom: 5px;" class="clearfix">
                                <div class="<?php echo ($value == 'Outra') ? "col-md-3" : "col-md-12"; ?>" style="padding-left: 0">
                                    <div class="checkbox check-default">
                                        <input type="checkbox" name="expectativas[]" id="expectativas<?php echo $key; ?>" value="<?php echo $value; ?>" <?php echo $checked; ?>>
                                        <label for="expectativas<?php echo $key; ?>" style="font-size: 12px"><?php echo $value; ?></label>
                                    </div>
                                </div>

                                <?php if($value == 'Outra'){ ?>
                                    <div class="col-md-9" style="padding-left: 0">
                                        <input type="text" class="input-sm" id="expectativas_outra" name="expectativas_outra" placeholder="" maxlength="50"
                                            value="<?php echo $outraValue; ?>">
                                    </div>
                                <?php } ?>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- BOTÕES-->
        <div class="container col-md-12" style="margin-top: 10px">
            <div class="row">
                <div class="col-md-4 text-left">
                    <a href="javascript:;" class="btn btn-primary btn-md activate-step" data-step="1">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        1º PASSO
                    </a>
                </div>
                <div class="col-md-4 text-center">
                    <a href="javascript:;" class="btn btn-danger btn-md save">
                        <i class="fa fa-floppy-o fa-fw" aria-hidden="true"></i>
                        Salvar Rascunho
                    </a>
                </div>
                <div class="col-md-4 text-right">
                    <a href="javascript:;" class="btn btn-primary btn-md activate-step" data-step="3">
                        3º PASSO
                        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>