<style>
    #table_length select,
    #table_filter input{
        width: auto;
    }
</style>
<div class="col-md-12">
    <div class="grid simple">
        <div class="grid-title no-border">
            <div class="row">
                <div id="container">
                    <div class="col-md-12">
                        <?php if(isset($this->projects) && !empty($this->projects)){ ?>
                            <table id="table" class="display" cellspacing="0" width="100%">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nome do Projeto</th>
                                <th>País(es)</th>
                                <th>Estado(s)</th>
                                <th>Cidade(s)</th>
                                <th>Status</th>
                                <th style="width: 110px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php foreach ($this->projects as $project){
                                switch (strtolower($project['status'])){
                                    case 'editando': $statusColor = 'gray'; break;
                                    case 'enviado': $statusColor = 'blue'; break;
                                    case 'inscrito': $statusColor = 'green'; break;
                                    case 'credenciado': $statusColor = 'darkblue'; break;
                                }
                                ?>
                                <tr>
                                    <td><?php echo $project['id']; ?></td>
                                    <td><?php echo $project['nome']; ?></td>
                                    <td><?php echo str_replace(',', ', ', $project['territorio']); ?></td>
                                    <td><?php echo str_replace(',', ', ', $project['estado']); ?></td>
                                    <td><?php echo str_replace(',', ', ', $project['cidade']); ?></td>
                                    <td><span style="color:<?php echo $statusColor; ?>; font-weight: bold"><?php echo strtoupper($project['status']); ?></span></td>
                                    <td>
                                        <a href="<?php echo $this->baseUrl('/projeto/detalhes/i/'. $project['id']); ?>" class="btn btn-primary btn-sm my-tooltip" data-toggle="tooltip" title="Detalhes do Projeto">
                                            <i class="fa fa-list-alt" aria-hidden="true"></i>
                                        </a>
                                        <?php if($project['status'] == 'editando'){ ?>
                                            <a href="<?php echo $this->baseUrl('/projeto/formulario/i/'. $project['id']); ?>" class="btn btn-primary btn-sm my-tooltip" data-toggle="tooltip" title="Editar Projeto">
                                                <i class="fa fa-edit" aria-hidden="true"></i>
                                            </a>
                                        <?php } ?>

                                        <?php if(in_array($project['status'], array('editando', 'enviado'))){ ?>
                                            <a href="<?php echo $this->baseUrl('/projeto/excluir/i/'. $project['id']); ?>" class="btn btn-primary btn-sm my-tooltip" data-toggle="tooltip" title="Deletar Projeto" onclick="return confirm('Tem certeza que deseja deletar este projeto?')">
                                                <i class="fa fa-times" aria-hidden="true"></i>
                                            </a>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                        <?php } else { ?>
                            <p class="text-center">Você não tem nenhum projeto, deseja cadastrar um agora? <a
                                    href="<?php echo $this->baseUrl('/projeto/cadastro'); ?>">Clique aqui</a>.</p>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#table').dataTable({
        "order": [[ 0, 'desc' ]],
        "language": { "url": "//cdn.datatables.net/plug-ins/1.10.13/i18n/Portuguese-Brasil.json" }
    });
</script>